export const sliderItems = [
  {
    id: 1,
    img: "https://i.ibb.co/qrZcQVL/t1-removebg-preview.png",
    title: "WINTER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "https://i.ibb.co/9vnkkZ0/t10-removebg-preview.png",
    title: "AWESOME GIFTS",
    desc: "GET A GREATE GIFTS! T-SHIRTS , MUGS , HATS , BAGS AND OTHER STUFF.",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://i.ibb.co/tqxXh9s/t12-removebg-preview.png",
    title: "FRIENDS FANS",
    desc: "HI FRIENDS FANS .. NOW WE CAN GET ALL STUFF THAT WE LOVED IN THIS UNIQUE TV SHOW !!",
    bg: "fbf0f4",
  },
];
export const categories = [
  {
    id: 1,
    img: "https://i.ibb.co/LgMx0dy/t6.jpg",
    title: "FASHION",
    to: "fashion",
  },
  {
    id: 2,
    img: "https://i.ibb.co/NYs8b1x/t4.jpg",
    title: "ACCESSORIES",
    to: "accessories",
  },
  {
    id: 3,
    img: "https://i.ibb.co/qjZVG3K/t8.jpg",
    title: "OTHER STUFF",
    to: "others",
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "https://i.ibb.co/wKrNnKb/s1.png",
    productName: "Friends Central Perk Tee",
    productDesc:
      "Represent your favorite Friends coffeehouse with this relaxed grey tee. It features a distressed version of the famous Central Perk logo!",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/wKrNnKb/s1.png",
      "https://i.ibb.co/qFTFbnn/s14.png",
      "https://i.ibb.co/WgFL9J0/s17.png",
    ],
    count: 1,
    productPrice: 30,
    type: "fashion",
    date: "2020-09-16",
  },
  {
    id: 2,
    img: "https://i.ibb.co/NFJfynr/s2.png",
    productName: "Friends - Pattern Tervis Tumbler",
    productDesc:
      "Could this Friends Pattern Tervis Tumbler BE any better for fans? Featuring a pattern of symbols that any Friends enthusiast will recognize and designed with a secure lid, this tumbler is perfect to use while on the go or during your next Friends marathon.",
    productColor: "red",
    productSize: "L",
    images: [
      "https://i.ibb.co/NFJfynr/s2.png",
      "https://i.ibb.co/D1XBYQZ/s19.png",
    ],
    count: 1,
    productPrice: 12,
    type: "other",
    date: "2020-11-02",
  },
  {
    id: 3,
    img: "https://i.ibb.co/yRkyhk2/s3.png",
    productName: "Friends Black Hat",
    productDesc:
      "Represent your favorite Friends in a chic black style that goes with every outfit. Whether you're playing football on Thanksgiving or relaxing on the beach (hopefully away from any jellyfish...), it's a versatile addition to your wardrobe. This hat was made exclusively for The Shop by Mitchell & Ness!",
    productColor: "lightblue",
    productSize: "L",
    images: [
      "https://i.ibb.co/yRkyhk2/s3.png",
      "https://i.ibb.co/5Lj8vPK/s7.png",
      "https://i.ibb.co/VSZxjMS/s8.png",
      "https://i.ibb.co/wJ5rh6q/s33.png",
    ],

    count: 1,
    productPrice: 32,
    date: "5-12-2020",
    type: "accessories",
    date: "2020-04-29",
  },
  {
    id: 4,
    img: "https://i.ibb.co/qxpqVTL/s4.png",
    productName: "Friends Central Perk Canvas Tote Bag",
    productDesc:
      "Headed out on a jaunt through your city - maybe stopping at your local coffeehouse for a pick-me-up? Rep your favorite fictional café from Friends with our vintage-inspired Central Perk tote.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/qxpqVTL/s4.png",
      "https://i.ibb.co/TmsNMY6/s35.png",
    ],
    count: 1,
    productPrice: 24,
    date: "2020-07-08",
    type: "accessories",
  },
  {
    id: 5,
    img: "https://i.ibb.co/ccxX3q4/s5.png",
    productName: "Friends Central Perk Mug",
    productDesc:
      "The Central Perk mugs on the show were uniquely oversized, and ours are no exception! Pour some coffee and pretend you're sitting at the coffee house with the gang.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/ccxX3q4/s5.png",
      "https://i.ibb.co/Y084zyn/s23.png",
    ],

    count: 1,
    productPrice: 26,
    date: "2020-02-20",
    type: "other",
  },
  {
    id: 6,
    img: "https://i.ibb.co/s53gw20/s6.png",
    productName: "Friends Central Perk Travel Mug",
    productDesc:
      "Take your love for Central Perk with you on the go with this Friends Central Perk Travel Mug. Featuring the iconic coffee house logo, this travel mug lets you enjoy a hot or cold beverage on the go.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/s53gw20/s6.png",
      "https://i.ibb.co/1RJF7nj/s18.png",
    ],
    count: 1,
    productPrice: 15,
    date: "2020-06-26",
    type: "other",
  },
  {
    id: 7,
    img: "https://i.ibb.co/5Lj8vPK/s7.png",
    productName: "Friends Frame Hat",
    productDesc:
      "If you're all about our West Village gang but want a cheeky way to show it, our frame hat is perfect for a show as iconic as Friends! This super comfy purple hat - the same color as Monica Geller's gorgeous apartment walls - also features the famous Friends frame.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/5Lj8vPK/s7.png",
      "https://i.ibb.co/yRkyhk2/s3.png",
      "https://i.ibb.co/VSZxjMS/s8.png",
      "https://i.ibb.co/wJ5rh6q/s33.png",
    ],
    count: 1,
    productPrice: 32,
    date: "2019-02-20",
    type: "accessories",
  },
  {
    id: 8,
    img: "https://i.ibb.co/VSZxjMS/s8.png",
    productName: "Friends Denim Hat",
    productDesc:
      "Denim was all the rage when Friends premiered, so we decided we had to do the trend justice with a funky denim hat (featuring the logo, of course!). The '90s are back in style - can't you just see Monica wearing this during their annual football game? Exclusively from Mitchell & Ness.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/VSZxjMS/s8.png",
      "https://i.ibb.co/yRkyhk2/s3.png",
      "https://i.ibb.co/5Lj8vPK/s7.png",
      "https://i.ibb.co/wJ5rh6q/s33.png",
    ],
    count: 1,
    productPrice: 32,
    date: "2019-10-06",
    type: "accessories",
  },
  {
    id: 9,
    img: "https://i.ibb.co/wSQs6zT/s20.png",
    productName: "Friends Color Change Umbrella",
    productDesc:
      "This Friends Color Change Umbrella is perfect to bring out during those rainy days. With color changing technology, this umbrella changes hues as it gets wet and dries. Fun and classic, this umbrella is sure to make your day, week, month, and even your year the best yet.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/wSQs6zT/s20.png",
      "https://i.ibb.co/vkxMzj8/s36.png",
    ],
    count: 1,
    productPrice: 32,
    date: "2020-07-14",
    type: "accessories",
  },
  {
    id: 10,
    img: "https://i.ibb.co/D1XBYQZ/s19.png",
    productName: "Friends - Central Perk Tervis Tumbler",
    productDesc:
      "From listening to the musical talents of Phoebe Buffay to enjoying a scone, you will love sipping your favorite beverage from this Central Perk Tervis Tumbler. With a secure lid and classic design, this tumbler is a must-have for any fan.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/D1XBYQZ/s19.png",
      "https://i.ibb.co/NFJfynr/s2.png",
    ],
    count: 1,
    productPrice: 12,
    date: "2020-09-12",
    type: "other",
  },
  {
    id: 11,
    img: "https://i.ibb.co/1RJF7nj/s18.png",
    productName: "Friends Travel Mug",
    productDesc:
      "Whether you are heading to work at Bloomingdales or hanging out at your best friend’s apartment, this Friends Travel Mug lets you represent your favorite Friends moments, icons, and phrases with each sip. Designed to securely hold your favorite beverages, this 16 oz. travel mug makes a great gift for Friends fans on the go.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/1RJF7nj/s18.png",
      "https://i.ibb.co/s53gw20/s6.png",
    ],
    count: 1,
    productPrice: 15,
    date: "2020-06-30",
    type: "other",
  },
  {
    id: 12,
    img: "https://i.ibb.co/WgFL9J0/s17.png",
    productName: "Friends Names Tee",
    productDesc:
      "They'll be there for you! This tribute to the titular characters of the iconic series Friends features the names of your favorite pack of Central Perk-loving pals -- making it the ideal piece to sport with your own BFF.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/WgFL9J0/s17.png",
      "https://i.ibb.co/qFTFbnn/s14.png",
      "https://i.ibb.co/wKrNnKb/s1.png",
    ],
    count: 1,
    productPrice: 30,
    date: "2020-08-05",
    type: "fashion",
  },
  {
    id: 13,
    img: "https://i.ibb.co/ZzJ2KwZ/s16.png",
    productName: "Friends Peephole Frame Squeaker Plush Dog Toy",
    productDesc:
      "Nothing says Friends quite like the eclectic decor of Monica's Manhattan apartment, and this squeaker toy for your favorite watch buddy pays homage to her purple door and gold peephole frame. Perfect for keeping your pooch entertained while you re-watch the series!",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/ZzJ2KwZ/s16.png",
      "https://i.ibb.co/2sN2kDD/s39.png",
      "https://i.ibb.co/syn5fC6/s26.png",
    ],
    count: 1,
    productPrice: 16,
    date: "2020-12-03",
    type: "accessories",
  },
  {
    id: 14,
    img: "https://i.ibb.co/K5GgmmM/s15.png",
    productName: "Friends Turkey Head Squeaker Plush Dog Toy",
    productDesc:
      "While the Gellers may not have eaten Thanksgiving turkey off of Joey's head, your pup almost definitely would have! Let your pet unleash their love for both poultry and Friends with this fun squeaker plush.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/K5GgmmM/s15.png",
      "https://i.ibb.co/K5GgmmM/s15.png",
    ],
    count: 1,
    productPrice: 21,
    date: "2020-04-14",
    type: "accessories",
  },
  {
    id: 15,
    img: "https://i.ibb.co/qFTFbnn/s14.png",
    productName: "Friends They Don't Know… Tee",
    productDesc:
      "One of the more confusing but most well known quotes immortalized in tee form, even if it always got Joey confused. Chandler & Monica forever (even if Ross, you know, didn't really agree with it at first)",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/qFTFbnn/s14.png",
      "https://i.ibb.co/WgFL9J0/s17.png",
      "https://i.ibb.co/wKrNnKb/s1.png",
    ],
    count: 1,
    productPrice: 30,
    date: "2020-03-06",
    type: "fashion",
  },
  {
    id: 16,
    img: "https://i.ibb.co/XxQjRzK/s13.png",
    productName: "Friends Central Perk Keychain",
    productDesc:
      "Take Central Perk with you everywhere you go! Rep your favorite coffeehouse on your keychain with this acrylic logo decoration.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/XxQjRzK/s13.png",
      "https://i.ibb.co/XxQjRzK/s13.png",
    ],
    count: 1,
    productPrice: 16,
    date: "2020-02-04",
    type: "accessories",
  },
  {
    id: 17,
    img: "https://i.ibb.co/tHkL1mN/s12.png",
    productName: "Friends Women's Mashup Tee",
    productDesc:
      "We mashed up all our favorite Friends quotes in Technicolor on this women's fit tee. Find your favorite - we're personally big fans of Ross Geller and PIVOT!",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/tHkL1mN/s12.png",
      "https://i.ibb.co/2khK6ZV/s10.png",
      "https://i.ibb.co/z4pvgXD/s29.png",
    ],
    count: 1,
    productPrice: 34,
    date: "2020-01-05",
    type: "fashion",
  },
  {
    id: 18,
    img: "https://i.ibb.co/gMvB50y/s11.png",
    productName: "Friends Icecap Hat",
    productDesc: "",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/gMvB50y/s11.png",
      "https://i.ibb.co/gMvB50y/s11.png",
    ],
    count: 1,
    productPrice: 30,
    date: "2020-01-01",
    type: "accessories",
  },
  {
    id: 19,
    img: "https://i.ibb.co/2khK6ZV/s10.png",
    productName: "Friends Soda Sharing Tee",
    productDesc:
      "Share a soda with the gang from Friends on this distressed, vintage-style tee. It's extra soft for long nights of watching your favorite episodes (especially wihle you're eating your own favorite dessert. Just remember - Joey doesn't share food!).",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/2khK6ZV/s10.png",
      "https://i.ibb.co/tHkL1mN/s12.png",
      "https://i.ibb.co/z4pvgXD/s29.png",
    ],
    count: 1,
    productPrice: 34,
    date: "2019-03-09",
    type: "fashion",
  },
  {
    id: 20,
    img: "https://i.ibb.co/xqKkzbF/s9.png",
    productName: "Friends Customizable Nalgene",
    productDesc:
      "If you're quoting Friends on a daily basis, this Nalgene is for you. From recurring jokes (hello, my name is Regina Phalange) to one-off favorite quotes, It's customizable for every fan. The bottle comes with a pack of stickers so you can decorate however you'd like!",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/xqKkzbF/s9.png",
      "https://i.ibb.co/xqKkzbF/s9.png",
    ],
    count: 1,
    productPrice: 24,
    date: "2020-04-25",
    type: "other",
  },
  {
    id: 21,
    img: "https://i.ibb.co/MZB64z0/s40.png",
    productName: "Friends Lobster Water Bottle",
    productDesc:
      "This Friends Lobster Water Bottle is sure to be any fan's lobster! Whether you go to the gym or run/flail your way through Central Park with your friend, this water bottle helps keep you hydrated with each sip.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/MZB64z0/s40.png",
      "https://i.ibb.co/MZB64z0/s40.png",
    ],
    count: 1,
    productPrice: 13,
    date: "2020-12-30",
    type: "other",
  },
  {
    id: 22,
    img: "https://i.ibb.co/2sN2kDD/s39.png",
    productName: "Friends I'll Be There Pillow",
    productDesc:
      "Featuring Chandler, Rachel, Ross, Monica, Joey, and Phoebe in the iconic milkshake photo, this Friends I'll Be There Pillow is a classic addition to your decor. No matter where you place it, this pillow will remind you that your friends are always there for you.",
    productColor: "red",
    productSize: "L",
    images: [
      "https://i.ibb.co/2sN2kDD/s39.png",
      "https://i.ibb.co/ZzJ2KwZ/s16.png",
      "https://i.ibb.co/syn5fC6/s26.png",
    ],

    count: 1,
    productPrice: 16,
    date: "2019-03-05",
    type: "accessories",
  },
  {
    id: 23,
    img: "https://i.ibb.co/Z63fsrk/s38.png",
    productName: "Friends Logo Socks",
    productDesc:
      "A pair for you, and a pair for your BFF. Whether your Friendship is more Monica & Rachel or Chandler & Joey, this two pack of Friends logo socks is the perfect way to show off your Friendship.",
    productColor: "lightblue",
    productSize: "L",
    images: [
      "https://i.ibb.co/Z63fsrk/s38.png",
      "https://i.ibb.co/2jwn8Bn/s37.png",
    ],
    count: 1,
    productPrice: 20,
    date: "2020-01-25",
    type: "accessories",
  },
  {
    id: 24,
    img: "https://i.ibb.co/2jwn8Bn/s37.png",
    productName: "Friends Logo Socks",
    productDesc:
      "A pair for you, and a pair for your BFF. Whether your Friendship is more Monica & Rachel or Chandler & Joey, this two pack of Friends logo socks is the perfect way to show off your Friendship.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/2jwn8Bn/s37.png",
      "https://i.ibb.co/Z63fsrk/s38.png",
    ],
    count: 1,
    productPrice: 20,
    date: "2019-12-06",
    type: "accessories",
  },
  {
    id: 25,
    img: "https://i.ibb.co/vkxMzj8/s36.png",
    productName: "Friends Logo Umbrella",
    productDesc:
      "We'll be there for you... when the rain starts to pour. Inspired by the ultra-famous Friends theme song (hello, Central Park in the rain!), we created this bright blue umbrella featuring the Friends logo as the perfect rainy day accessory.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/vkxMzj8/s36.png",
      "https://i.ibb.co/wSQs6zT/s20.png",
    ],
    count: 1,
    productPrice: 32,
    date: "2019-09-15",
    type: "accessories",
  },
  {
    id: 26,
    img: "https://i.ibb.co/TmsNMY6/s35.png",
    productName: "Friends Polka Dot Logo Tote Bag",
    productDesc:
      "This canvas tote features the iconic Friends logo amidst bursts of color. It's the perfect cheerful tote for work, errands, or the grocery store.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/TmsNMY6/s35.png",
      "https://i.ibb.co/qxpqVTL/s4.png",
    ],
    count: 1,
    productPrice: 24,
    date: "2020-10-11",
    type: "accessories",
  },
  {
    id: 27,
    img: "https://i.ibb.co/23knTSz/s34.png",
    productName: "Friends Frame Shaped Mug",
    productDesc:
      "If there is one thing more iconic than the Friends characters themselves, it is the yellow frame hanging on Monica’s apartment door. Featuring the yellow frame placed on top of a peephole, this fully-functional purple mug is a must-have for Friends fans. Whether you keep it at home or take it to the office, everyone will know the meaning behind this oversized mug.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/23knTSz/s34.png",
      "https://i.ibb.co/kg1T4sw/s32.png",
    ],
    count: 1,
    productPrice: 25,
    date: "2020-05-26",
    type: "other",
  },
  {
    id: 28,
    img: "https://i.ibb.co/wJ5rh6q/s33.png",
    productName: "Friends White Hat",
    productDesc:
      "This bright white hat is perfect for summer days wandering around your hometown. You could even bring it with you on your next visit to NYC - next stop, West Village & the Friends apartment!",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/wJ5rh6q/s33.png",
      "https://i.ibb.co/5Lj8vPK/s7.png",
      "https://i.ibb.co/VSZxjMS/s8.png",
      "https://i.ibb.co/yRkyhk2/s3.png",
    ],
    count: 1,
    productPrice: 32,
    date: "2020-05-09",
    type: "accessories",
  },
  {
    id: 29,
    img: "https://i.ibb.co/kg1T4sw/s32.png",
    productName: "Friends Lobster Mug and Socks",
    productDesc:
      "He’s her lobster! Perfect for the #1 Friends fans, this Friends Lobster Mug and Socks makes an excellent holiday, birthday, or “just because” gift to your lobster. Whether they wear these cozy socks during a Friends marathon or sip their Central Perk coffee from the pink and white mug, fans of Friends will love showing off this bundle every chance they get!",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/kg1T4sw/s32.png",
      "https://i.ibb.co/23knTSz/s34.png",
    ],
    count: 1,
    productPrice: 25,
    date: "2020-02-14",
    type: "other",
  },
  {
    id: 30,
    img: "https://i.ibb.co/DRLqTCb/s31.png",
    productName: "Friends Central Perk Apron",
    productDesc:
      "Picked up baking recently? Cooking? Accident-prone? Channel your inner Monica Geller (or Rachel Green, depending on which side you fall on...) with this Central Perk apron, perfect for any Friends lover's kitchen.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/DRLqTCb/s31.png",
      "https://i.ibb.co/DRLqTCb/s31.png",
    ],
    count: 1,
    productPrice: 28,
    date: "2020-08-05",
    type: "accessories",
  },
  {
    id: 31,
    img: "https://i.ibb.co/G714914/s30.png",
    productName: "Friends You're My Lobster T-Shirt",
    productDesc:
      "Shop from our Friends X Cakeworthy collection, like this Lobster t-shirt featuring Ross and Rachel, available now.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/G714914/s30.png",
      "https://i.ibb.co/GsKB6p1/s25.png",
      "https://i.ibb.co/6npTYtW/s24.png",
      "https://i.ibb.co/WD3hHPt/s22.png",
    ],

    count: 1,
    productPrice: 50,
    date: "2020-12-04",
    type: "fashion",
  },
  {
    id: 32,
    img: "https://i.ibb.co/z4pvgXD/s29.png",
    productName: "Friends Turkey Tee",
    productDesc:
      "Friends is famous for their Thanksgiving episodes, so of course we had to make a tee for it! This soft grey tee features the iconic turkey from Season 5, Episode 8:The One With All The Thanksgivings. It's much easier to wear the turkey on a shirt than on your head!",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/z4pvgXD/s29.png",
      "https://i.ibb.co/2khK6ZV/s10.png",
      "https://i.ibb.co/tHkL1mN/s12.png",
    ],
    count: 1,
    productPrice: 34,
    date: "2020-12-27",
    type: "fashion",
  },
  {
    id: 33,
    img: "https://i.ibb.co/BqNMg4s/s28.png",
    productName: "Friends We Know Tote",
    productDesc:
      "Grab this iconic tote bag featuring the quote, They don't know that we now they know we know.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/BqNMg4s/s28.png",
      "https://i.ibb.co/MSQPDb2/s27.png",
      "https://i.ibb.co/KK1sKXS/s21.png",
    ],
    count: 1,
    productPrice: 50,
    date: "2020-07-04",
    type: "accessories",
  },
  {
    id: 34,
    img: "https://i.ibb.co/MSQPDb2/s27.png",
    productName: "Friends Pla Tote",
    productDesc:
      "Shop Friends apparel like this officially licensed tote from Cakeworthy featuring Phoebe's quote,I don't even have a pla‚",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/MSQPDb2/s27.png",
      "https://i.ibb.co/KK1sKXS/s21.png",
      "https://i.ibb.co/BqNMg4s/s28.png",
    ],
    count: 1,
    productPrice: 50,
    date: "2020-07-07",
    type: "accessories",
  },
  {
    id: 35,
    img: "https://i.ibb.co/syn5fC6/s26.png",
    productName: "Friends I'll Be There Pillow",
    productDesc:
      "Featuring Chandler, Rachel, Ross, Monica, Joey, and Phoebe in the iconic milkshake photo, this Friends I'll Be There Pillow is a classic addition to your decor. No matter where you place it, this pillow will remind you that your friends are always there for you.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/syn5fC6/s26.png",
      "https://i.ibb.co/ZzJ2KwZ/s16.png",
      "https://i.ibb.co/2sN2kDD/s39.png",
    ],
    count: 1,
    productPrice: 16,
    date: "2020-08-04",
    type: "accessories",
  },
  {
    id: 36,
    img: "https://i.ibb.co/GsKB6p1/s25.png",
    productName: "Friends Unagi T-Shirt",
    productDesc:
      "Shop official Friends licensed products at Cakeworthy, like this Unagi pocket tee featuring Rachel, Phoebe, and Ross.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/GsKB6p1/s25.png",
      "https://i.ibb.co/6npTYtW/s24.png",
      "https://i.ibb.co/WD3hHPt/s22.png",
      "https://i.ibb.co/G714914/s30.png",
    ],
    count: 1,
    productPrice: 50,
    date: "2020-12-20",
    type: "fashion",
  },
  {
    id: 37,
    img: "https://i.ibb.co/6npTYtW/s24.png",
    productName: "Friends Long Sleeve T-Shirt",
    productDesc:
      "Could I be wearing anymore clothes? Shop officially licensed Friends apparel like this hilarious long-sleeve t-shirt featuring the iconic scene where Joey puts on all of Chandler's clothes.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/6npTYtW/s24.png",
      "https://i.ibb.co/WD3hHPt/s22.png",
      "https://i.ibb.co/G714914/s30.png",
      "https://i.ibb.co/GsKB6p1/s25.png",
    ],
    count: 1,
    productPrice: 50,
    date: "2020-03-08",
    type: "fashion",
  },
  {
    id: 38,
    img: "https://i.ibb.co/Y084zyn/s23.png",
    productName: "Friends Logo Mug",
    productDesc:
      "We'll be there for you.. and all your coffee needs. Sip out of this black logo mug while you kick back and rewatch your favorite episodes!",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/Y084zyn/s23.png",
      "https://i.ibb.co/ccxX3q4/s5.png",
    ],
    count: 1,
    productPrice: 26,
    date: "2020-02-01",
    type: "other",
  },
  {
    id: 39,
    img: "https://i.ibb.co/WD3hHPt/s22.png",
    productName: "Friends Vintage Style Pullover Sweater",
    productDesc:
      "Shop officially licensed Friends apparel like this vintage-style pullover sweater featuring the whole gang, available now at Cakeworthy.",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/WD3hHPt/s22.png",
      "https://i.ibb.co/G714914/s30.png",
      "https://i.ibb.co/GsKB6p1/s25.png",
      "https://i.ibb.co/6npTYtW/s24.png",
    ],
    count: 1,
    productPrice: 50,
    date: "2020-01-05",
    type: "fashion",
  },
  {
    id: 40,
    img: "https://i.ibb.co/KK1sKXS/s21.png",
    productName: "Friends We Were On a Break Tote",
    productDesc:
      "Shop the Friends X Cakeworthy collection starring t-shirts, flannels, and even tote bags like this denim tote featuring the legendary quote, We were on a break!",
    productColor: "Black",
    productSize: "L",
    images: [
      "https://i.ibb.co/KK1sKXS/s21.png",
      "https://i.ibb.co/MSQPDb2/s27.png",
      "https://i.ibb.co/BqNMg4s/s28.png",
    ],
    count: 1,
    productPrice: 50,
    date: "2019-12-06",
    type: "accessories",
  },
];
